from colorama import Fore

def logo_text():
    print(Fore.CYAN + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print(Fore.CYAN + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print(Fore.CYAN +"+++++++++" + Fore.RED + "OOOOOO" + Fore.CYAN + "++++++++++++" +Fore.RED +  "O" + Fore.CYAN + "++++++++++++" + Fore.RED +  "O" + Fore.CYAN + "++" + Fore.RED +  "OOOOOOOO" + Fore.CYAN + "++" + Fore.RED +  Fore.RED +"OOO" + Fore.CYAN + "++++++" + Fore.RED +  "O" + Fore.CYAN +"+++++++")
    print(Fore.CYAN +"++++++++" + Fore.RED +  "O" + Fore.CYAN + "+++++++++++++++++++" + Fore.RED + "O" + Fore.CYAN + "++++++++++" + Fore.RED + "O" + Fore.CYAN + "+++" + Fore.RED + "O" + Fore.CYAN + "+++++++" + Fore.RED + "O" + Fore.CYAN + "+" + Fore.RED + "O" + Fore.CYAN + "++" + Fore.RED + "O" + Fore.CYAN + "+++++" + Fore.RED + "O"+ Fore.CYAN + "+++++++")
    print(Fore.CYAN +"++++++++" + Fore.RED + "O" + Fore.CYAN + "++++++++++++++++++++" + Fore.RED + "O" + Fore.CYAN + "++++++++" + Fore.RED + "O" + Fore.CYAN + "++++" + Fore.RED + "O"+ Fore.CYAN + "+++++++" + Fore.RED + "O" + Fore.CYAN + "+" + Fore.RED + "O"+ Fore.CYAN + "+++" + Fore.RED + "O" + Fore.CYAN + Fore.CYAN + "++++" + Fore.RED + "O" + Fore.CYAN + "+++++++")
    print(Fore.CYAN +"+++++++++" + Fore.RED + "OOOOOOO" + Fore.CYAN + "+++++" + Fore.RED + "OOOOO" + Fore.CYAN + "++++" + Fore.RED + "O" + Fore.CYAN + "++++++" + Fore.RED + "O" + Fore.CYAN + "+++++" + Fore.RED + "OOOOOOOO" + Fore.CYAN + "++" + Fore.RED + "O" + Fore.CYAN + "++++" + Fore.RED + "O" + Fore.CYAN + "+++" + Fore.RED + "O" + Fore.CYAN + "+++++++")
    print(Fore.CYAN +"++++++++++++++++" + Fore.RED + "O" + Fore.CYAN + "++++++++++++++" + Fore.RED + "O" + Fore.CYAN + "++++" + Fore.RED + "O" + Fore.CYAN + "++++++" + Fore.RED + "O" + Fore.CYAN + "+++++++++" + Fore.RED + "O" + Fore.CYAN + "+++++" + Fore.RED + "O" + Fore.CYAN + "++" + Fore.RED + "O" + Fore.CYAN + "+++++++")
    print(Fore.CYAN +"++++++++++++++++" + Fore.RED + "O" + Fore.CYAN + "+++++++++++++++" + Fore.RED + "O" + Fore.CYAN + "++" + Fore.RED + "O" + Fore.CYAN + "+++++++" + Fore.RED + "O" + Fore.CYAN + "+++++++++" + Fore.RED + "O" + Fore.CYAN + "++++++" + Fore.RED + "O" + Fore.CYAN + "+" + Fore.RED + "O" + Fore.CYAN + "+++++++")
    print(Fore.CYAN + "++++++++" + Fore.RED + "OOOOOOOO" + Fore.CYAN + Fore.CYAN + "+++++++++++++++++" + Fore.RED + "OO" + Fore.CYAN + "++++++++" + Fore.RED + "O" + Fore.CYAN + "+++++++++" + Fore.RED + "O" + Fore.CYAN + "+++++++" + Fore.RED + "OO" + Fore.CYAN + "+++++++")
    print(Fore.CYAN + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print(Fore.CYAN + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("\n\t\t\t\t\t\t\tVersion 0.0.1\n")